name: Build Crystal Bitoreum Wallet

on:
  push:
    branches:
      - 4.0.0.0
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        arch: [x86_64, aarch64]
    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.arch }} on ${{ matrix.os }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          git curl build-essential libtool autotools-dev automake \
          pkg-config python3 bsdmainutils cmake libdb-dev libdb++-dev \
          screen zlib1g-dev wget

    - name: Build and install Python 3.10.17
      run: |
        cd /usr/src
        sudo wget https://www.python.org/ftp/python/3.10.17/Python-3.10.17.tgz
        sudo tar xzf Python-3.10.17.tgz
        cd Python-3.10.17
        sudo ./configure --enable-optimizations
        sudo make -j$(nproc)
        sudo make altinstall
        echo "alias python=python3.10" >> ~/.bashrc
        echo "alias python3=python3.10" >> ~/.bashrc
        export PATH="/usr/bin:$PATH"
        python3.10 --version

    - name: Set up directories
      run: |
        mkdir -p ~/bitoreum-build/compressed

    - name: Build depends
      run: |
        cd depends
        make -j$(nproc) HOST=${{ matrix.arch }}-pc-linux-gnu

    - name: Autogen & Configure
      run: |
        ./autogen.sh
        ./configure --prefix=$(pwd)/depends/${{ matrix.arch }}-pc-linux-gnu

    - name: Compile Wallet
      run: |
        make -j$(nproc)

    - name: Prepare Binaries
      run: |
        VERSION=4.0.0.0
        COIN_NAME=bitoreum
        BUILD_DIR=~/bitoreum-build/build
        COMPRESS_DIR=~/bitoreum-build/compressed
        mkdir -p ${BUILD_DIR} ${BUILD_DIR}_not_strip ${BUILD_DIR}_debug

        cp src/{bitoreum-cli,bitoreumd,bitoreum-tx,qt/bitoreum-qt} ${BUILD_DIR}
        cp src/{bitoreum-cli,bitoreumd,bitoreum-tx,qt/bitoreum-qt} ${BUILD_DIR}_not_strip
        strip ${BUILD_DIR}/*

        make clean && make distclean
        ./autogen.sh
        ./configure --prefix=$(pwd)/depends/${{ matrix.arch }}-pc-linux-gnu --disable-tests --enable-debug
        make -j$(nproc)
        cp src/{bitoreum-cli,bitoreumd,qt/bitoreum-qt} ${BUILD_DIR}_debug

    - name: Create Archives and Checksums
      run: |
        VERSION=4.0.0.0
        COIN_NAME=bitoreum
        BUILD_DIR=~/bitoreum-build/build
        COMPRESS_DIR=~/bitoreum-build/compressed
        ARCH_TYPE=${{ matrix.arch }}
        OS=${{ matrix.os }}

        for type in "" "_debug" "_not_strip"; do
          DIR="${BUILD_DIR}${type}"
          FILENAME="${COIN_NAME}-${OS}_${ARCH_TYPE}${type//_/-}-${VERSION}.tar.gz"
          cd "$DIR"
          echo "sha256:" > checksums.txt
          echo "------------------------------------" >> checksums.txt
          shasum * >> checksums.txt
          echo "------------------------------------" >> checksums.txt
          echo "openssl-sha256:" >> checksums.txt
          echo "------------------------------------" >> checksums.txt
          sha256sum * >> checksums.txt
          tar -cf - -C "$DIR" . | gzip -9 > "$COMPRESS_DIR/$FILENAME"
        done

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bitoreum-${{ matrix.os }}-${{ matrix.arch }}-wallets
        path: ~/bitoreum-build/compressed/*.tar.gz
