name: Full Crystal Bitoreum Build

on:
  push:
    branches:
      - main
      - dev
      - 4.0.*
  pull_request:
    branches:
      - main
      - dev
      - 4.0.*
  workflow_dispatch:

env:
  COIN_NAME: bitoreum
  BUILD_DIR: bitoreum-build
  COMPRESS_DIR: bitoreum-compress
  TEST_DIR: bitoreum-test

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  get-version:
    name: Get Version
    runs-on: ubuntu-latest
    steps:
      - name: Triggered By
        run: |
          echo "checking out $GITHUB_REF triggered by $GITHUB_EVENT_NAME"
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Version Logic
        id: selected-version
        run: |
          VERSION=$(grep '^release-version=' build.properties | cut -d'=' -f2)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "BUILD_VERSION=$VERSION" > version.txt
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: version.txt

    outputs:
      version: ${{ steps.selected-version.outputs.version }}

  build-ubuntu24-x86:
    name: Ubuntu 24 x86 Build
    needs: get-version
    runs-on: ubuntu-24.04
    env:
      ARCH_TYPE: x86
      OS: ubuntu-24.04
      BUILD_DIR: build
      COMPRESS_DIR: compress
      TEST_DIR: test
      COIN_NAME: bitoreum
      RELEASE_DIR: bitoreum-v${{ needs.get-version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Required Packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl build-essential libtool autotools-dev automake pkg-config python3 bsdmainutils cmake
      - name: Build Depends
        run: |
          echo "building with $(nproc) threads"
          make -C depends -j$(nproc) HOST=x86_64-pc-linux-gnu
      - name: Configure
        run: |
          ./autogen.sh
          ./configure --prefix=$(pwd)/depends/x86_64-pc-linux-gnu
      - name: Build Binaries
        run: |
          make -j$(nproc)
          mkdir -p ${BUILD_DIR} ${BUILD_DIR}_not_strip ${TEST_DIR}
          cp src/{bitoreum-cli,bitoreumd,bitoreum-tx,qt/bitoreum-qt} ${BUILD_DIR}/
          cp src/{bitoreum-cli,bitoreumd,bitoreum-tx,qt/bitoreum-qt} ${BUILD_DIR}_not_strip/
          cp src/test/test_bitoreum ${TEST_DIR}
          strip ${BUILD_DIR}/* || true
      - name: Build Debug Binaries
        run: |
          make clean
          make distclean
          ./autogen.sh
          ./configure --prefix=$(pwd)/depends/x86_64-pc-linux-gnu --disable-tests --enable-debug
          make -j$(nproc)
          mkdir -p ${BUILD_DIR}_debug
          cp src/{bitoreum-cli,bitoreumd,bitoreum-tx,qt/bitoreum-qt} ${BUILD_DIR}_debug/
      - name: Organize Artifacts
        run: |
          mkdir -p ${RELEASE_DIR}
          for dir in "${BUILD_DIR}" "${BUILD_DIR}_debug" "${BUILD_DIR}_not_strip"; do
            case $dir in
              *debug) suffix="debug" ;;
              *_not_strip) suffix="notstrip" ;;
              *) suffix="release" ;;
            esac
            target="${RELEASE_DIR}/${suffix}"
            mkdir -p "$target"
            cp $dir/bitoreum-cli $dir/bitoreumd $dir/bitoreum-qt $dir/bitoreum-tx "$target/"
            pushd "$target"
            echo "sha256:" > checksums.txt
            shasum bitoreum-cli bitoreumd bitoreum-qt bitoreum-tx >> checksums.txt
            echo "openssl-sha256:" >> checksums.txt
            sha256sum bitoreum-cli bitoreumd bitoreum-qt bitoreum-tx >> checksums.txt
            popd
          done
      - name: Compress Artifacts
        run: |
          mkdir -p ${COMPRESS_DIR}
          pushd $(dirname ${RELEASE_DIR})
          rel_dir=$(basename ${RELEASE_DIR})
          for suffix in release debug notstrip; do
            tar -czf ../${COIN_NAME}-${OS}-${ARCH_TYPE}-${suffix}-${{ needs.get-version.outputs.version }}.tar.gz ${rel_dir}/${suffix}
          done
          popd
          mv *.tar.gz ${COMPRESS_DIR}/
          cd ${COMPRESS_DIR}
          for f in *.tar.gz; do
            echo "$f" >> checksums.txt
            echo "sha256: $(shasum $f)" >> checksums.txt
            echo "openssl-sha256: $(sha256sum $f)" >> checksums.txt
          done
          cat checksums.txt
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.COIN_NAME }}-${{ env.OS }}-${{ env.ARCH_TYPE }}-${{ needs.get-version.outputs.version }}
          path: ${{ env.COMPRESS_DIR }}
      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.COIN_NAME }}-${{ env.OS }}-${{ env.ARCH_TYPE }}-test-${{ needs.get-version.outputs.version }}
          path: ${{ env.TEST_DIR }}


  build-ubuntu22-x86:
    name: Ubuntu 22 x86 Build
    needs: get-version
    runs-on: ubuntu-22.04
    env:
      ARCH_TYPE: x86
      OS: ubuntu-22.04
      BUILD_DIR: build
      COMPRESS_DIR: compress
      TEST_DIR: test
      COIN_NAME: bitoreum
      RELEASE_DIR: bitoreum-v${{ needs.get-version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Required Packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl build-essential libtool autotools-dev automake pkg-config python3 bsdmainutils cmake
      - name: Build Depends
        run: |
          echo "building with $(nproc) threads"
          make -C depends -j$(nproc) HOST=x86_64-pc-linux-gnu
      - name: Configure
        run: |
          ./autogen.sh
          ./configure --prefix=$(pwd)/depends/x86_64-pc-linux-gnu
      - name: Build Binaries
        run: |
          make -j$(nproc)
          mkdir -p ${BUILD_DIR} ${BUILD_DIR}_not_strip ${TEST_DIR}
          cp src/{bitoreum-cli,bitoreumd,bitoreum-tx,qt/bitoreum-qt} ${BUILD_DIR}/
          cp src/{bitoreum-cli,bitoreumd,bitoreum-tx,qt/bitoreum-qt} ${BUILD_DIR}_not_strip/
          cp src/test/test_bitoreum ${TEST_DIR}
          strip ${BUILD_DIR}/* || true
      - name: Build Debug Binaries
        run: |
          make clean
          make distclean
          ./autogen.sh
          ./configure --prefix=$(pwd)/depends/x86_64-pc-linux-gnu --disable-tests --enable-debug
          make -j$(nproc)
          mkdir -p ${BUILD_DIR}_debug
          cp src/{bitoreum-cli,bitoreumd,bitoreum-tx,qt/bitoreum-qt} ${BUILD_DIR}_debug/
      - name: Organize Artifacts
        run: |
          mkdir -p ${RELEASE_DIR}
          for dir in "${BUILD_DIR}" "${BUILD_DIR}_debug" "${BUILD_DIR}_not_strip"; do
            case $dir in
              *debug) suffix="debug" ;;
              *_not_strip) suffix="notstrip" ;;
              *) suffix="release" ;;
            esac
            target="${RELEASE_DIR}/${suffix}"
            mkdir -p "$target"
            cp $dir/bitoreum-cli $dir/bitoreumd $dir/bitoreum-qt $dir/bitoreum-tx "$target/"
            pushd "$target"
            echo "sha256:" > checksums.txt
            shasum bitoreum-cli bitoreumd bitoreum-qt bitoreum-tx >> checksums.txt
            echo "openssl-sha256:" >> checksums.txt
            sha256sum bitoreum-cli bitoreumd bitoreum-qt bitoreum-tx >> checksums.txt
            popd
          done
      - name: Compress Artifacts
        run: |
          mkdir -p ${COMPRESS_DIR}
          pushd $(dirname ${RELEASE_DIR})
          rel_dir=$(basename ${RELEASE_DIR})
          for suffix in release debug notstrip; do
            tar -czf ../${COIN_NAME}-${OS}-${ARCH_TYPE}-${suffix}-${{ needs.get-version.outputs.version }}.tar.gz ${rel_dir}/${suffix}
          done
          popd
          mv *.tar.gz ${COMPRESS_DIR}/
          cd ${COMPRESS_DIR}
          for f in *.tar.gz; do
            echo "$f" >> checksums.txt
            echo "sha256: $(shasum $f)" >> checksums.txt
            echo "openssl-sha256: $(sha256sum $f)" >> checksums.txt
          done
          cat checksums.txt
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.COIN_NAME }}-${{ env.OS }}-${{ env.ARCH_TYPE }}-${{ needs.get-version.outputs.version }}
          path: ${{ env.COMPRESS_DIR }}
      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.COIN_NAME }}-${{ env.OS }}-${{ env.ARCH_TYPE }}-test-${{ needs.get-version.outputs.version }}
          path: ${{ env.TEST_DIR }}

  build-win64:
    name: Win64 x86 Build
    needs: get-version
    runs-on: ubuntu-22.04
    env:
      ARCH_TYPE: x86
      OS: win64
      RELEASE_DIR: bitoreum-v${{ needs.get-version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Required Packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl build-essential libtool autotools-dev automake pkg-config python3 bsdmainutils cmake
          sudo apt-get install -y g++-mingw-w64-x86-64 gcc-mingw-w64-x86-64 nsis
          sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
      - name: Build Depends
        run: |
          echo "building with $(nproc) threads"
          make -C depends -j$(nproc) HOST=x86_64-w64-mingw32
      - name: Configure
        run: |
          ./autogen.sh
          ./configure --prefix=$(pwd)/depends/x86_64-w64-mingw32
      - name: Build Binaries
        run: |
          make -j$(nproc)
          mkdir -p ${BUILD_DIR} ${BUILD_DIR}_not_strip ${TEST_DIR}
          cp src/{bitoreum-cli.exe,bitoreumd.exe,bitoreum-tx.exe,qt/bitoreum-qt.exe} ${BUILD_DIR}/
          mv src/{bitoreum-cli.exe,bitoreumd.exe,bitoreum-tx.exe,qt/bitoreum-qt.exe} ${BUILD_DIR}_not_strip/
          mv src/test/test_bitoreum.exe ${TEST_DIR}
          strip ${BUILD_DIR}/* || true
      - name: Build Debug Binaries
        run: |
          make clean
          make distclean
          ./autogen.sh
          ./configure --prefix=$(pwd)/depends/x86_64-w64-mingw32 --disable-tests --enable-debug
          make -j$(nproc)
          mkdir -p ${BUILD_DIR}_debug
          cp src/{bitoreum-cli.exe,bitoreumd.exe,bitoreum-tx.exe,qt/bitoreum-qt.exe} ${BUILD_DIR}_debug/
      - name: Organize Artifacts
        run: |
          mkdir -p ${RELEASE_DIR}/release ${RELEASE_DIR}/notstrip ${RELEASE_DIR}/debug
          cp ${BUILD_DIR}/*.exe ${RELEASE_DIR}/release/
          cp ${BUILD_DIR}_not_strip/*.exe ${RELEASE_DIR}/notstrip/
          cp ${BUILD_DIR}_debug/*.exe ${RELEASE_DIR}/debug/
          for d in release notstrip debug; do
            pushd ${RELEASE_DIR}/$d
            echo "sha256:" > checksums.txt
            shasum *.exe >> checksums.txt
            echo "openssl-sha256:" >> checksums.txt
            sha256sum *.exe >> checksums.txt
            popd
          done
      - name: Compress Artifacts
        run: |
          mkdir -p ${COMPRESS_DIR}
          pushd $(dirname ${RELEASE_DIR})
          rel_dir=$(basename ${RELEASE_DIR})
          for d in release notstrip debug; do
            zip -r ../${COIN_NAME}-${OS}-${ARCH_TYPE}-${d}-${{ needs.get-version.outputs.version }}.zip ${rel_dir}/$d
          done
          popd
          mv *.zip ${COMPRESS_DIR}/
          cd ${COMPRESS_DIR}
          for f in *.zip; do
            echo "$f" >> checksums.txt
            echo "sha256: $(shasum $f)" >> checksums.txt
            echo "openssl-sha256: $(sha256sum $f)" >> checksums.txt
          done
          cat checksums.txt
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.COIN_NAME }}-${{ env.OS }}-${{ env.ARCH_TYPE }}-${{ needs.get-version.outputs.version }}
          path: ${{ env.COMPRESS_DIR }}

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.COIN_NAME }}-${{ env.OS }}-${{ env.ARCH_TYPE }}-test-${{ needs.get-version.outputs.version }}
          path: ${{ env.TEST_DIR }}

      - name: Generate Windows Installation File
        run: |
          make deploy
          mkdir -p win64-installation
          mv *.exe win64-installation/
          cd win64-installation
          final="Crystal-Bitoreum-win64-install-${{ needs.get-version.outputs.version }}.exe"
          installer=$(ls *.exe | grep -v test | head -n 1)
          mv "$installer" "$final"
          echo "sha256: $(shasum $final)" >> checksums.txt
          echo "openssl-sha256: $(sha256sum $final)" >> checksums.txt
          cat checksums.txt
          mkdir -p ../${RELEASE_DIR}/installer
          cp "$final" ../${RELEASE_DIR}/installer/
          cp checksums.txt ../${RELEASE_DIR}/installer/
      - name: Upload Win64 Installation File
        uses: actions/upload-artifact@v4
        with:
          name: Crystal-Bitoreum-win64-install-${{ needs.get-version.outputs.version }}
          path: win64-installation
  
  build-ubuntu22-arm64:
    name: Ubuntu 22 ARM64 Build
    needs: get-version
    runs-on: ubuntu-22.04
    env:
      ARCH_TYPE: arm64
      OS: ubuntu-22.04
      BUILD_DIR: build
      COMPRESS_DIR: compress
      TEST_DIR: test
      COIN_NAME: bitoreum
      RELEASE_DIR: bitoreum-v${{ needs.get-version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Required Packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl build-essential libtool autotools-dev automake pkg-config python3 bsdmainutils cmake g++-aarch64-linux-gnu
      - name: Build Depends
        run: |
          echo "building with $(nproc) threads"
          make -C depends -j$(nproc) HOST=aarch64-linux-gnu
      - name: Configure
        run: |
          ./autogen.sh
          ./configure --prefix=$(pwd)/depends/aarch64-linux-gnu --host=aarch64-linux-gnu
      - name: Build Binaries
        run: |
          make -j$(nproc)
          mkdir -p ${BUILD_DIR} ${BUILD_DIR}_not_strip ${TEST_DIR}
          cp src/{bitoreum-cli,bitoreumd,bitoreum-tx,qt/bitoreum-qt} ${BUILD_DIR}/
          cp src/{bitoreum-cli,bitoreumd,bitoreum-tx,qt/bitoreum-qt} ${BUILD_DIR}_not_strip/
          cp src/test/test_bitoreum ${TEST_DIR}
          strip ${BUILD_DIR}/* || true
      - name: Build Debug Binaries
        run: |
          make clean
          make distclean
          ./autogen.sh
          ./configure --prefix=$(pwd)/depends/aarch64-linux-gnu --host=aarch64-linux-gnu --disable-tests --enable-debug
          make -j$(nproc)
          mkdir -p ${BUILD_DIR}_debug
          cp src/{bitoreum-cli,bitoreumd,bitoreum-tx,qt/bitoreum-qt} ${BUILD_DIR}_debug/
      - name: Organize Artifacts
        run: |
          mkdir -p ${RELEASE_DIR}
          for dir in "${BUILD_DIR}" "${BUILD_DIR}_debug" "${BUILD_DIR}_not_strip"; do
            case $dir in
              *debug) suffix="debug" ;;
              *_not_strip) suffix="notstrip" ;;
              *) suffix="release" ;;
            esac
            target="${RELEASE_DIR}/${suffix}"
            mkdir -p "$target"
            cp $dir/bitoreum-cli $dir/bitoreumd $dir/bitoreum-qt $dir/bitoreum-tx "$target/"
            pushd "$target"
            echo "sha256:" > checksums.txt
            shasum bitoreum-cli bitoreumd bitoreum-qt bitoreum-tx >> checksums.txt
            echo "openssl-sha256:" >> checksums.txt
            sha256sum bitoreum-cli bitoreumd bitoreum-qt bitoreum-tx >> checksums.txt
            popd
          done
      - name: Compress Artifacts
        run: |
          mkdir -p ${COMPRESS_DIR}
          pushd $(dirname ${RELEASE_DIR})
          rel_dir=$(basename ${RELEASE_DIR})
          for suffix in release debug notstrip; do
            tar -czf ../${COIN_NAME}-${OS}-${ARCH_TYPE}-${suffix}-${{ needs.get-version.outputs.version }}.tar.gz ${rel_dir}/${suffix}
          done
          popd
          mv *.tar.gz ${COMPRESS_DIR}/
          cd ${COMPRESS_DIR}
          for f in *.tar.gz; do
            echo "$f" >> checksums.txt
            echo "sha256: $(shasum $f)" >> checksums.txt
            echo "openssl-sha256: $(sha256sum $f)" >> checksums.txt
          done
          cat checksums.txt
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.COIN_NAME }}-${{ env.OS }}-${{ env.ARCH_TYPE }}-${{ needs.get-version.outputs.version }}
          path: ${{ env.COMPRESS_DIR }}
      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.COIN_NAME }}-${{ env.OS }}-${{ env.ARCH_TYPE }}-test-${{ needs.get-version.outputs.version }}
          path: ${{ env.TEST_DIR }}

          
  build-ubuntu24-arm64:
    name: Ubuntu 24 ARM64 Build
    needs: get-version
    runs-on: ubuntu-24.04
    env:
      ARCH_TYPE: arm64
      OS: ubuntu-24.04
      BUILD_DIR: build
      COMPRESS_DIR: compress
      TEST_DIR: test
      COIN_NAME: bitoreum
      RELEASE_DIR: bitoreum-v${{ needs.get-version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Required Packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl build-essential libtool autotools-dev automake pkg-config python3 bsdmainutils cmake g++-aarch64-linux-gnu
      - name: Build Depends
        run: |
          echo "building with $(nproc) threads"
          make -C depends -j$(nproc) HOST=aarch64-linux-gnu
      - name: Configure
        run: |
          ./autogen.sh
          ./configure --prefix=$(pwd)/depends/aarch64-linux-gnu --host=aarch64-linux-gnu
      - name: Build Binaries
        run: |
          make -j$(nproc)
          mkdir -p ${BUILD_DIR} ${BUILD_DIR}_not_strip ${TEST_DIR}
          cp src/{bitoreum-cli,bitoreumd,bitoreum-tx,qt/bitoreum-qt} ${BUILD_DIR}/
          cp src/{bitoreum-cli,bitoreumd,bitoreum-tx,qt/bitoreum-qt} ${BUILD_DIR}_not_strip/
          cp src/test/test_bitoreum ${TEST_DIR}
          strip ${BUILD_DIR}/* || true
      - name: Build Debug Binaries
        run: |
          make clean
          make distclean
          ./autogen.sh
          ./configure --prefix=$(pwd)/depends/aarch64-linux-gnu --host=aarch64-linux-gnu --disable-tests --enable-debug
          make -j$(nproc)
          mkdir -p ${BUILD_DIR}_debug
          cp src/{bitoreum-cli,bitoreumd,bitoreum-tx,qt/bitoreum-qt} ${BUILD_DIR}_debug/
      - name: Organize Artifacts
        run: |
          mkdir -p ${RELEASE_DIR}
          for dir in "${BUILD_DIR}" "${BUILD_DIR}_debug" "${BUILD_DIR}_not_strip"; do
            case $dir in
              *debug) suffix="debug" ;;
              *_not_strip) suffix="notstrip" ;;
              *) suffix="release" ;;
            esac
            target="${RELEASE_DIR}/${suffix}"
            mkdir -p "$target"
            cp $dir/bitoreum-cli $dir/bitoreumd $dir/bitoreum-qt $dir/bitoreum-tx "$target/"
            pushd "$target"
            echo "sha256:" > checksums.txt
            shasum bitoreum-cli bitoreumd bitoreum-qt bitoreum-tx >> checksums.txt
            echo "openssl-sha256:" >> checksums.txt
            sha256sum bitoreum-cli bitoreumd bitoreum-qt bitoreum-tx >> checksums.txt
            popd
          done
      - name: Compress Artifacts
        run: |
          mkdir -p ${COMPRESS_DIR}
          pushd $(dirname ${RELEASE_DIR})
          rel_dir=$(basename ${RELEASE_DIR})
          for suffix in release debug notstrip; do
            tar -czf ../${COIN_NAME}-${OS}-${ARCH_TYPE}-${suffix}-${{ needs.get-version.outputs.version }}.tar.gz ${rel_dir}/${suffix}
          done
          popd
          mv *.tar.gz ${COMPRESS_DIR}/
          cd ${COMPRESS_DIR}
          for f in *.tar.gz; do
            echo "$f" >> checksums.txt
            echo "sha256: $(shasum $f)" >> checksums.txt
            echo "openssl-sha256: $(sha256sum $f)" >> checksums.txt
          done
          cat checksums.txt
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.COIN_NAME }}-${{ env.OS }}-${{ env.ARCH_TYPE }}-${{ needs.get-version.outputs.version }}
          path: ${{ env.COMPRESS_DIR }}

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.COIN_NAME }}-${{ env.OS }}-${{ env.ARCH_TYPE }}-test-${{ needs.get-version.outputs.version }}
          path: ${{ env.TEST_DIR }}
          
  build-macos-13-x86:
    name: macOS 13 x86 Build
    needs: get-version
    runs-on: macos-13

    env:
      RELEASE_DIR: bitoreum-v${{ needs.get-version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Required Packages
        run: |
          brew install automake libtool pkg-config miniupnpc librsvg libnatpmp zeromq python
          pip3 install ds_store mac_alias
          pip3 install -U pip setuptools

      - name: Build Depends
        run: |
          echo "building with 8 threads"
          make -C depends -j8 HOST=x86_64-apple-darwin22

      - name: Configure
        run: |
          ./autogen.sh
          ./configure --prefix=$(pwd)/depends/x86_64-apple-darwin22

      - name: Build Binaries
        run: |
          make -j8
          mkdir -p ${BUILD_DIR} ${BUILD_DIR}_not_strip ${TEST_DIR}
          cp src/{bitoreum-cli,bitoreumd,bitoreum-tx,qt/bitoreum-qt} ${BUILD_DIR}/
          mv src/{bitoreum-cli,bitoreumd,bitoreum-tx,qt/bitoreum-qt} ${BUILD_DIR}_not_strip/
          mv src/test/test_bitoreum ${TEST_DIR}
          strip ${BUILD_DIR}/*

      - name: Organize Artifacts
        run: |
          mkdir -p ${RELEASE_DIR}/release ${RELEASE_DIR}/notstrip
          cp ${BUILD_DIR}/* ${RELEASE_DIR}/release/
          cp ${BUILD_DIR}_not_strip/* ${RELEASE_DIR}/notstrip/
          for d in release notstrip; do
            pushd ${RELEASE_DIR}/$d
            echo "sha256:" > checksums.txt
            shasum * >> checksums.txt
            echo "openssl-sha256:" >> checksums.txt
            openssl sha256 * >> checksums.txt
            popd
          done
      - name: Compress Artifacts
        run: |
          mkdir -p ${COMPRESS_DIR}
          pushd $(dirname ${RELEASE_DIR})
          rel_dir=$(basename ${RELEASE_DIR})
          for d in release notstrip; do
            tar -czf ../${COIN_NAME}-macOS13-x86-${d}-${{ needs.get-version.outputs.version }}.tar.gz ${rel_dir}/$d
          done
          popd
          mv *.tar.gz ${COMPRESS_DIR}/
          cd ${COMPRESS_DIR}
          for f in *.tar.gz; do
            echo "$f" >> checksums.txt
            echo "sha256: $(shasum $f)" >> checksums.txt
            echo "openssl-sha256: $(openssl sha256 $f | awk '{print $2}')" >> checksums.txt
          done
          cat checksums.txt
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.COIN_NAME }}-macOS13-x86-${{ needs.get-version.outputs.version }}
          path: ${{ env.COMPRESS_DIR }}

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.COIN_NAME }}-macOS13-x86-test-${{ needs.get-version.outputs.version }}
          path: ${{ env.TEST_DIR }}

      - name: Generate Macos dmg files
        run: |
          make deploy
          mkdir -p macos-dmg
          mv Bitoreum-Qt.dmg macos-dmg/Crystal-Bitoreum-Qt.dmg
          cd macos-dmg
          echo "sha256: $(shasum Crystal-Bitoreum-Qt.dmg)" >> checksums.txt
          echo "openssl-sha256: $(openssl sha256 Crystal-Bitoreum-Qt.dmg)" >> checksums.txt
          cd ..

      - name: Upload dmg file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.COIN_NAME }}-macOS13-x86-dmg-${{ needs.get-version.outputs.version }}
          path: macos-dmg
