---
name: Bitoreum Build

on:
  push:
    branches:
      - 4.0.0
  pull_request:
    branches:
      - 4.0.0
  workflow_dispatch:

env:
  COIN_NAME: bitoreum
  BUILD_DIR: bitoreum-build
  COMPRESS_DIR: bitoreum-compress
  TEST_LOG_ARTIFACT_DIR: test-logs

jobs:
  checking-build-version:
    name: Checking Build Versioning
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read release version (main)
        if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
        id: release-version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: build.properties
          property: 'release-version'

      - name: Read snapshot version (pull_request/develop)
        if: ${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/develop' }}
        id: snapshot-version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: build.properties
          property: 'snapshot-version'

      - name: Create version file
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "BUILD_VERSION=${{ steps.release-version.outputs.value }}" > version.txt
          else
            echo "BUILD_VERSION=${{ steps.snapshot-version.outputs.value }}" > version.txt
          fi

      - name: Upload version artifact
        uses: actions/upload-artifact@v3
        with:
          name: version
          path: version.txt

  build-ubuntu22:
    name: Ubuntu 22.04 Build
    needs: checking-build-version
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: version

      - name: Export BUILD_VERSION
        run: echo "$(cat version.txt)" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            curl build-essential libtool autotools-dev automake pkg-config python3 bsdmainutils cmake \
            libevent-dev libboost-all-dev libssl-dev libzmq3-dev libminiupnpc-dev \
            libprotobuf-dev protobuf-compiler libqrencode-dev libdb-dev libdb++-dev

      - name: Build depends
        run: make -C depends -j$(nproc)

      - name: Configure
        run: |
          ./autogen.sh
          ./configure --prefix=$(pwd)/depends/x86_64-pc-linux-gnu

      - name: Build binaries
        run: |
          make -j$(nproc)
          mkdir -p $BUILD_DIR
          mv src/{bitoreum-cli,bitoreum-tx,bitoreumd,qt/bitoreum-qt} $BUILD_DIR/
          strip $BUILD_DIR/* || true

      - name: Create checksums and compress
        run: |
          cd $BUILD_DIR
          for bin in bitoreum-cli bitoreumd bitoreum-tx bitoreum-qt; do
            shasum $bin >> checksums.txt
            sha256sum $bin >> checksums.txt
          done
          cd ..
          tar -czvf ${COIN_NAME}-ubuntu22-${BUILD_VERSION}.tar.gz $BUILD_DIR
          mkdir -p $COMPRESS_DIR
          mv ${COIN_NAME}-ubuntu22-${BUILD_VERSION}.tar.gz $COMPRESS_DIR/
          sha256sum ${COMPRESS_DIR}/${COIN_NAME}-ubuntu22-${BUILD_VERSION}.tar.gz >> ${COMPRESS_DIR}/checksums.txt

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.COIN_NAME }}-ubuntu22-${{ env.BUILD_VERSION }}
          path: ${{ env.COMPRESS_DIR }}

# ... (Leave macOS and Windows unchanged or modernize if needed as above)
