name: Build Crystal Bitoreum Wallet

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 4.0.0.0

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            arch: x86_64
            host: x86_64-pc-linux-gnu

          - os: ubuntu-20.04
            arch: arm64
            host: aarch64-linux-gnu

          - os: ubuntu-22.04
            arch: x86_64
            host: x86_64-pc-linux-gnu

          - os: ubuntu-22.04
            arch: arm64
            host: aarch64-linux-gnu

          - os: ubuntu-24.04
            arch: x86_64
            host: x86_64-pc-linux-gnu

          - os: ubuntu-24.04
            arch: arm64
            host: aarch64-linux-gnu

          - os: macos-12
            arch: x86_64
            host: x86_64-apple-darwin

          - os: macos-14
            arch: arm64
            host: arm64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt update && sudo apt install -y \
            git curl build-essential libtool autotools-dev automake pkg-config \
            bsdmainutils cmake libdb-dev libdb++-dev zlib1g-dev python3 \
            g++-aarch64-linux-gnu binutils-aarch64-linux-gnu zip

      - name: Install Python 3.10 (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          cd /usr/src
          sudo wget https://www.python.org/ftp/python/3.10.17/Python-3.10.17.tgz
          sudo tar xzf Python-3.10.17.tgz
          cd Python-3.10.17
          sudo ./configure --enable-optimizations
          sudo make -j$(nproc)
          sudo make altinstall

      - name: Install Dependencies (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew update
          brew install automake libtool pkg-config cmake zip openssl@3

      - name: Clone & Build Depends
        run: |
          mkdir -p ~/bitoreum-build
          cd ~/bitoreum-build
          git clone https://github.com/Nikovash/bitoreum -b 4.0.0.0
          cd bitoreum/depends
          make -j$(nproc) HOST=${{ matrix.host }}

      - name: Configure & Build Wallet
        run: |
          cd ~/bitoreum-build/bitoreum
          ./autogen.sh
          ./configure --prefix=$(pwd)/depends/${{ matrix.host }} --host=${{ matrix.host }}
          make -j$(nproc)

      - name: Package Wallet
        run: |
          VERSION=4.0.0.0
          COIN_NAME=bitoreum
          BUILD_DIR="$HOME/bitoreum-build/build"
          COMPRESS_DIR="$HOME/bitoreum-build/compressed"
          OS_NAME="${{ matrix.os }}-${{ matrix.arch }}"

          mkdir -p "$BUILD_DIR" "$COMPRESS_DIR"

          cp src/bitoreum* "$BUILD_DIR" 2>/dev/null || true
          cp src/qt/bitoreum-qt* "$BUILD_DIR" 2>/dev/null || true

          cd "$BUILD_DIR"
          echo "sha256:" > checksums.txt
          echo "------------------------------------" >> checksums.txt
          (sha256sum * 2>/dev/null || shasum * ) >> checksums.txt

          if [[ "${{ matrix.os }}" == macos-* ]]; then
            ZIP_NAME="${COIN_NAME}-${OS_NAME}-${VERSION}.zip"
            zip -r "$COMPRESS_DIR/$ZIP_NAME" ./*
          else
            TAR_NAME="${COIN_NAME}-${OS_NAME}-${VERSION}.tar.gz"
            tar -czf "$COMPRESS_DIR/$TAR_NAME" ./*
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bitoreum-${{ matrix.os }}-${{ matrix.arch }}
          path: ~/bitoreum-build/compressed/*
