name: Crystal Bitoreum Core Wallet Build

on:
  workflow_dispatch:
  push:
    branches:
      - 4.0.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os_version: [22.04, 24.04]
        arch: [x86_64, aarch64]

    name: Build for Ubuntu ${{ matrix.os_version }} (${{ matrix.arch }})
    container:
      image: ubuntu:${{ matrix.os_version }}
    steps:
      - name: Install dependencies
        run: |
          apt update && apt dist-upgrade -y
          apt install -y \
            git curl build-essential libtool autotools-dev automake pkg-config \
            python3 bsdmainutils cmake libdb-dev libdb++-dev screen zlib1g-dev \
            wget tar make gcc g++

      - name: Install Python 3.10.17
        run: |
          cd /usr/src
          wget https://www.python.org/ftp/python/3.10.17/Python-3.10.17.tgz
          tar xzf Python-3.10.17.tgz
          cd Python-3.10.17
          ./configure --enable-optimizations
          make -j$(nproc)
          make altinstall
          ln -sf /usr/local/bin/python3.10 /usr/bin/python3
          ln -sf /usr/local/bin/python3.10 /usr/bin/python

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: Nikovash/bitoreum
          ref: 4.0.0.0
          path: bitoreum

      - name: Build Depends
        run: |
          cd bitoreum/depends
          echo "building with $(nproc) threads"
          make -j$(nproc) HOST=${{ matrix.arch }}-pc-linux-gnu

      - name: Configure and Build
        run: |
          cd bitoreum
          ./autogen.sh
          ./configure --prefix=$(pwd)/depends/${{ matrix.arch }}-pc-linux-gnu
          make -j$(nproc)

      - name: Package Artifacts
        run: |
          VERSION=4.0.0.0
          COIN_NAME=bitoreum
          ARCH_TYPE=${{ matrix.arch }}
          OS=ubuntu-${{ matrix.os_version }}

          BUILD_DIR="$HOME/bitoreum-build/build"
          COMPRESS_DIR="$HOME/bitoreum-build/compressed"
          mkdir -p "$BUILD_DIR" "${BUILD_DIR}_not_strip" "${BUILD_DIR}_debug" "$COMPRESS_DIR"

          cp bitoreum/src/{bitoreum-cli,bitoreumd,bitoreum-tx,qt/bitoreum-qt} "$BUILD_DIR"
          cp bitoreum/src/{bitoreum-cli,bitoreumd,bitoreum-tx,qt/bitoreum-qt} "$BUILD_DIR_not_strip"
          strip "$BUILD_DIR"/*

          cd bitoreum
          make clean && make distclean
          ./autogen.sh
          ./configure --prefix=$(pwd)/depends/${{ matrix.arch }}-pc-linux-gnu --disable-tests --enable-debug
          make -j$(nproc)
          mv src/{bitoreum-cli,bitoreumd,qt/bitoreum-qt} "$BUILD_DIR"_debug/

          for type in "" "_debug" "_not_strip"; do
            cd "$BUILD_DIR$type"
            echo "sha256:" > checksums.txt
            echo "------------------------------------" >> checksums.txt
            shasum * >> checksums.txt
            echo "------------------------------------" >> checksums.txt
            echo "openssl-sha256:" >> checksums.txt
            echo "------------------------------------" >> checksums.txt
            sha256sum * >> checksums.txt
            tar -cf - -C "$BUILD_DIR$type" . | gzip -9 > "$COMPRESS_DIR/${COIN_NAME}-${OS}_${ARCH_TYPE}${type}-${VERSION}.tar.gz"
          done

          cd "$COMPRESS_DIR"
          echo "sha256: shasum ${COIN_NAME}-${OS}_${ARCH_TYPE}-${VERSION}.tar.gz" >> checksums.txt
          echo "openssl-sha256: sha256sum ${COIN_NAME}-${OS}_${ARCH_TYPE}-${VERSION}.tar.gz" >> checksums.txt
          echo "sha256: shasum ${COIN_NAME}-${OS}_${ARCH_TYPE}-debug-${VERSION}.tar.gz" >> checksums.txt
          echo "openssl-sha256: sha256sum ${COIN_NAME}-${OS}_${ARCH_TYPE}-debug-${VERSION}.tar.gz" >> checksums.txt
          echo "sha256: shasum ${COIN_NAME}-${OS}_${ARCH_TYPE}-not_strip-${VERSION}.tar.gz" >> checksums.txt
          echo "openssl-sha256: sha256sum ${COIN_NAME}-${OS}_${ARCH_TYPE}-not_strip-${VERSION}.tar.gz" >> checksums.txt
          cat checksums.txt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bitoreum-${{ matrix.os_version }}-${{ matrix.arch }}
          path: ~/bitoreum-build/compressed/
